spring:
  application:
    name: console-api
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    # 设为false无法访问SwaggerUI，设为true无法使用截获异常进行404统一处理
    add-mappings: true
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 500MB
  session:
    redis:
      namespace: console-api
    store-type: redis
server:
  port: 8001
  max-http-header-size: 200MB
  tomcat:
    max-http-form-post-size: -1

logging:
  level:
    com.senior.dao: DEBUG

mybatis:
  mapper-locations: classpath*:mybatis/mappers/*.xml
  type-aliases-package: com.senior.domain

management:
  endpoints:
    web:
      exposure:
        include: 'prometheus'
  metrics:
    tags:
      application: ${spring.application.name}


